services:
  client:
    build:
      context: ../../
      dockerfile: apps/client/docker/production/Dockerfile
    depends_on:
      - database
    networks:
      - app_network
    ports:
      - 3000:3000

  database:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    build:
      context: ../../
      dockerfile: apps/server/docker/production/Dockerfile
    depends_on:
      - database
    networks:
      - app_network
    ports:
      - 4000:4000

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
